project:
  type: website

website:
  title: "Zurich R User Group"
  navbar:
    left:
      - text: "Give a Talk"
        href: https://github.com/blubb
      - text: "Host a Meetup"
        href: https://github.com/blubb
      - text: "About"
        href: https://github.com/blubb  
format:
  html:
    theme: cosmo
    css: styles.css



